version: '3'

volumes:
  mysql:
    driver: local
  solr:
    driver: local
  assets:
    driver: local

services:

  mysql:
    restart: always
    image: mysql:5.7
    env_file: .env_deployment
    volumes:
      - mysql:/var/lib/mysql

  solr:
    restart: always
    image: ualbertalib/blacklight_solr_conf
    volumes:
      - solr:/opt/solr/server/solr/mycores

  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1025:1025"
      - "3082:1080"

  # Rails
  web:
    image: ualbertalib/discovery:cataloguing
    depends_on:
      - mysql
      - solr
    env_file: .env_deployment
    volumes:
      - assets:/app/public/assets/
    restart: always
    ports:
      - "3002:80"
