# Needed and used by blacklight for the webapp
default: &default
  url: <%= Rails.application.secrets.solr_url %>

development:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
uat:
  <<: *default
production:
  <<: *default
  
