'659': ''
'588': ''
'637': Aboriginal Sports and Recreation
'102': Accounting & Taxation
'108': Adult Education
'511': Advertising
'95': Agriculture
'180': Agriculture, Life & Environmental Sciences
'512': Alberta Business & Economics
'106': All Education Databases
'21': Anatomy
'1': Anesthesia and Pain Control
'607': Anglais langue seconde
'624': Animal Science
'576': Anthropologie
'53': Anthropology
'54': Area Studies
'56': Art, Architecture and Design
'655': Arts et langues
'578': Auteurs canadiens-français
'636': Autochtones
'489': Beaux-Arts et sciences humaines
'22': Biochemistry
'23': Bioethics
'84': Biological Sciences
'535': Biological Sciences Basic
'634': Biologie
'24': Biomedical Engineering
'595': Books in Print and National Bibliographies
'572': Business Ethics
'653': Business History
'649': Business News Articles
'609': Business Research Article Database
'29': c
'513': Canadian Business & Economics
'611': Canadian Indian Treaties
'173': Canadian Studies
'25': Cell Biology
'118': Chemical Engineering
'86': Chemistry
'119': Civil and Environmental Engineering
'57': Classics
'651': Commodities
'527': Communications and Technology
'652': Company Directories
'141': Company Financials, Filings and Analysis
'593': Complementary and Alternative Medicine
'87': Computing Science
'514': Consumer Behaviour
'644': Corporate Funding (IPO, PE, VC, Debt)
'594': Corporate Governance
'645': Corporate M&A, Jt. Ventures, Bankruptcy
'646': Corporate Ownership
'144': Country Information
'531': Court Cases - Indexes & Full Text
'109': Curriculum and Instruction (K-12)
'27': Dental Hygiene
'26': Dentistry
'368': Dermatology
'488': Divers
'592': Dix bases de données incontournables
'58': Drama
'408': E-Commerce
'88': Earth & Atmospheric Sciences
'168': East Asian Languages and Literature
'174': East Asian Studies
'515': Economic Statistics
'59': Economics
'597': Economie
'516': Edmonton Business Resources
'656': "Éducation"
'638': Education (Elementary)
'639': Education (Secondary)
'107': Educational Administration & Leadership
'110': Educational Psychology
'120': Electrical and Computer Engineering
'647': Emerging Markets
'517': Energy
'290': Engineering (General)
'448': Engineering Management
'121': Engineering Physics
'60': English Language & Literature
'621': Environnement
'640': Espagnol
'579': "Études classiques"
'580': "Études de la religion"
'177': European Studies
'209': Evidence-Based Practice
'648': Executive Compensation
'28': Family Medicine
'61': Film and Media
'643': Folklore
'96': Food and Nutrition
'97': Forestry
'606': Francophonie canadienne
'536': French
'560': French - Canadian Literature
'557': French - Digital and Electronic Collections
'558': French - French Literature
'561': French - Language, Translation, and Media
'562': French - News, Business, and Society
'563': French - Reference Works
'622': Geographie
'210': Geriatrics and Gerontology
'169': Germanic Languages and Literatures
'602': Global Health
'149': Government Documents
'211': Health Policy
'30': Health Promotion
'179': Health Sciences (General)
'581': Histoire canadienne
'600': Histoire de l'Afrique francophone
'616': Histoire de l'Europe - Construction et identité européennes
'626': Histoire de l'Europe - Construction et identité européennes
'31': History of Medicine and the Health Sciences
'228': History of Science and Technology
'389': History, British
'62': History, Canada and United States
'63': History, General
'98': Human Ecology
'142': Human Resources
'178': Humanities and Social Sciences (General)
'188': ILL
'189': ILL_extended
'599': Images
'428': Indigenous and First Nations Education
'143': Industry
'103': Industry Financial Ratios
'642': Information gouvernementale
'520': Information Technology
'112': Instructional Technology
'76': Interdisciplinary
'538': Italian
'529': Jurisdiction - Canada
'530': Jurisdiction - Foreign & International
'32': Laboratory Medicine & Pathology
'518': Labour Relations and Labour Law
'64': Languages & Literatures
'550': Latin America Studies-Sociology/Women Studies
'551': Latin American Studies
'540': Latin American Studies - Business and News
'541': Latin American Studies - Caribbean
'546': Latin American Studies - Lang., Literature & Media
'545': Latin American Studies - Statistics
'549': Latin American Studies-Political Science/History
'148': Law (General)
'620': Law (test)
'528': Legislation
'113': Library and Information Studies
'65': Linguistics
'635': Littérature grise
'519': Management and Organizational Theory
'77': Maps and Cartographic Material
'654': Market Research Reports
'104': Marketing
'553': Materials Science & Engineering
'91': Mathematical Sciences
'122': Mechanical Engineering
'33': Medical Genetics
'34': Medical Microbiology and Immunology
'35': Medicine
'176': Middle Eastern and African Studies
'123': Mining and Petroleum Engineering
'66': Music
'582': Musique
'508': Nanoscience and Nanotechnology
'615': Native Arts &amp; Culture
'610': Native Beliefs, Religion &amp; Ceremony
'612': Native Biographies
'618': Native Education
'617': Native Health
'308': Native Health in Canada
'613': Native History
'614': Native Language &amp; Literature
'67': Native Studies
'629': Neuropsychologie humaine
'36': Neuroscience
'37': Nursing
'212': Nutrition
'38': Obstetrics and Gynaecology
'388': Occupational Medicine
'39': Occupational Therapy
'40': Oncology
'41': Ophthalmology
'208': Orthopedics
'42': Paediatrics
'532': Periodicals & Documents - Indexes & Full Text
'44': Pharmacology
'43': Pharmacy & Pharmaceutical Science
'583': Philosophie
'68': Philosophy
'114': Physical Education & Recreation
'45': Physical Therapy
'93': Physics
'46': Physiology
'510': Plant Science
'78': Polar Studies
'69': Political Science
'47': Psychiatry
'604': Psychologie de l'éducation
'627': Psychologie de la croissance
'70': Psychology
'573': Public and Not-for-Profit Organizations
'48': Public Health
'650': Public Opinion
'49': Radiology and Diagnostic Imaging
'534': Reference
'50': Rehabilitation Medicine
'71': Religion
'99': Renewable Resources
'100': Resource Economics and Environmental Sociology
'249': Ressources en francais
'574': Resumes/Interviews
'522': Retailing
'171': Romance Languages and Literatures
'83': Science (General)
'584': Science Politique
'657': Sciences
'591': Sciences de l'éducation
'585': Sciences de la santé
'658': Sciences humaines et sociales
'628': Sciences infirmieres
'509': Sciences naturelles
'492': Sciences sociales
'229': Slavic and East European Studies
'172': Slavic Languages and Literatures
'147': Small Business
'74': Social Work
'586': Sociologie
'73': Sociology
'587': Soins infirmiers
'571': Space Exploration (With Emphasis on Mars)
'564': Spanish and Portuguese
'566': Spanish&Portuguese- Language, Translation, & Media
'565': Spanish&Portuguese-Digital&Electronic Collections
'568': Spanish&Portuguese-Luso-Brazilian Literature
'569': Spanish&Portuguese-News, Business, and Society
'570': Spanish&Portuguese-Spanish Literature
'115': Special Education
'51': Speech Pathology and Audiology
'603': Sports Medicine
'230': Standards
'72': Statistics
'524': Stock Markets & Indexes
'533': Subject Access to Legal Resources
'52': Surgery
'268': Temporary
'116': TESL - Teaching English as a Second Language
'598': Theatre
'111': Theoretical, Cultural & International Studies
'630': TICE
'213': Toxicology
'525': Trade
'608': Traduction
'526': Women in Business
'75': Women&#039;s Studies
'641': Writing Studies
