aegeo:  Alberta Geological Survey
aginternet: Alberta Government Library - Internet
agl_cap:  Alberta Government Library - Capital Boulevard
agl_com:  Alberta Government Library - Commerce Place
agl_gwl:  Alberta Government Library - Great West Life
agl_lb: Alberta Government Library - Labour Building
agl_mnc:  Alberta Government Library - Monenco Bldg Calgary
agl_ncc:  Alberta Government Library - Neil Crawford Centre
agl_ssp:  Alberta Government Library - 107 Street
agl_tpn:  Alberta Government Library - Telus Plaza North
ahs_ahe: Alberta Health Services - Alberta Hospital Edmonton
ahs_centen: Alberta Health Services - Centennial Centre
ahs_rah:  Alberta Health Services - Royal Alexandra Hospital
ahs_reddr: Alberta Health Services - Red Deer Regional Hospital
ahs_sturg: Alberta Health Services - Sturgeon Community Hospital
ahsglenrse: Alberta Health Services - Glenrose Rehabilitation Hospital
aitf_calg:  Alberta Innovates - Technology Futures - Calgary
aitf_c-fer: Alberta Innovates - Technology Futures - C-FER Technologies
aitf_devon: Alberta Innovates - Technology Futures - Devon
aitf_mw: Alberta Innovates - Technology Futures - Mill Woods
aitf_veg: Alberta Innovates - Technology Futures - Vegreville
concordia:  Concordia University College
concordsem: Concordia Lutheran Seminary
covenantgn: Covenant Health - Grey Nuns Community Hospital
covenantmh: Covenant Health - Misericordia Community Hospital
cross:  Cross Cancer Institute
cuc:  Canadian University College
gprc: Grande Prairie Regional College
gprc_frvw: Grande Prairie Regional College - Fairview
gprc_int: Grande Prairie Regional College - Internet
gr_mac_acc: Grant MacEwan University - Alberta College Campus
gr_mac_cac: Grant MacEwan University - Centre for Arts & Communications
gr_mac_int: Grant MacEwan University - Internet
gr_mac_soc: Grant MacEwan University - South Campus
gr_macewan: Grant MacEwan University - City Centre Campus
justice_ca: Justice Canada
keyano: Keyano College
kings:  The King's University College
lakelnd_ll: Lakeland College Lloydminster
lakelnd_vr: Lakeland College Vermilion
newman: Newman Theological College
olds: Olds College
red_deer_c: Red Deer College
taylor: Taylor College and Seminary
uaarchives: University of Alberta Archives
uaaug: University of Alberta Augustana
uabard: University of Alberta Book and Record Depository
uabsj: University of Alberta Bibliotheque Saint-Jean
uabusiness: University of Alberta Winspear Business
uaeduc: University of Alberta HT Coutts Education
uahlthsc: University of Alberta JW Scott Health Sciences
uahss:  University of Alberta Rutherford-Humanities & Social Science
uainternet: University of Alberta Internet
ualaw: University of Alberta JA Weir Law
uamath: University of Alberta Mathematics
uascitech: University of Alberta Cameron - Science & Technology
uasjc:  University of Alberta St Joseph's College
uaspcoll: University of Alberta Bruce Peel Special Collections
uatechserv: University of Alberta Bibliographic Services
