aginternet: "Alberta Government Library - Internet"
agl_cap: "Alberta Government Library - Internet"
agl_gwl: "Alberta Government Library - Capital Boulevard"
agl_ssp: "Alberta Government Library - Great West Life"
agl_tpn: "Alberta Government Library - Telus Plaza"
ahs_ahe: "Alberta Health Services - Alberta Hospital Edmonton"
ahs_centen: "Alberta Health Services - Centennial Centre"
ahs_erc: "Alberta Health Services - Education Resource Centre"
ahs_mhrh: "Alberta Health Services - Medicine Hat Regional Hospital"
ahs_qeii: "Alberta Health Services - Queen Elizabeth II Hospital"
ahs_rah: "Alberta Health Services - Royal Alexandra Hospital"
ahs_reddr: "Alberta Health Services - Red Deer Regional Hospital"
ahs_sturg: "Alberta Health Services - Sturgeon-In Transition-Expect Delays"
ahsglenrse: "Alberta Health Services - Glenrose Rehabilitation Hospital"
aitf_calg: "Alberta Innovates - Technology Futures - Calgary"
aitf_c-fer: "Alberta Innovates - Technology Futures - C-Fer Technologies"
aitf_mw: "Alberta Innovates - Technology Futures - Mill Woods"
aitf_veg: "Alberta Innovates - Technology Futures - Vegreville"
concordia: "Concordia University College"
concordsem: "Concordia Lutheran Seminary"
covenantgn: "Covenant Health - Grey Nuns Community Hospital"
covenantmh: "Covenant Health - Misericordia Community Hospital"
cross: "Alberta Health Services - Cross Cancer Institute"
cuc: "canadian University College"
gprc_frvw: "Grande Prairie Regional College - Fairview"
gprc_gp: "Grande Prairie Regional College - Grande Prairie"
gprc_int: "Grande Prairie Regional College - Internet"
gr_mac_acc: "Macewan University - Alberta College Campus"
gr_mac_cac: "Macewan University - Centre for Arts & Communications"
gr_mac_int: "Macewan University - Internet"
gr_marc_soc: "Macewan University South Campus-On the Move-Expect Delay"
gr_mac_tsv: "Macewan University - Technical Services"
gr_macewan: "Macewan University - City Centre Campus"
keyano: "Keyano College"
kings: "King's University"
king: "King's University"
lakelnd_ll: "Lakeland College Lloydminster"
lakelnd_vr: "Llakeland College Vermilion"
neos_free: "NEOS Free Internet Resources"
newman: "Newman Theological College"
norq_main: "Norquest College - Main Building"
norq_west: "Norquest College - Westmount"
olds: "Olds College"
red_deer_c: "Red Deer College"
taylor: "Vanguard College - Taylor"
uaarchives: "University of Alberta Archives"
uaaug: "University of Alberta Augustana"
uabard: "University of Alberta Book and Record Depository"
uabsj: "University of Alberta Bibliotheque Saint-Jean"
uabusiness: "University of Alberta Winspear Business"
uaeduc: "University of Alberta HT Coutts Education"
uahlthsc: "University of Alberta JW Scott Health Sciences"
uahss: "University of Alberta Rutherford - Humanities & Social Science"
uainternet: "University of Alberta Internet"
ualaw: "University of Alberta JA Weir Law"
uamath: "University of Alberta Cameron - Mathematics"
uascitech: "University of Alberta Cameron - Science & Technology"
uasjc: "University of Alberta St Joseph's College"
uaspcoll: "University of Alberta Bruce Peel Special Collections"
uatechserv: "University of Alberta Bibliographic Services"
vanguard: "Vanguard College"
