aginternet: "alberta government library - internet"
agl_cap: "alberta government library - internet"
agl_gwl: "alberta government library - capital boulevard"
agl_ssp: "alberta government library - great west life"
agl_tpn: "alberta government library - telus plaza"
ahs_ahe: "alberta health services - alberta hospital edmonton"
ahs_centen: "alberta health services - centennial centre"
ahs_erc: "alberta health services - education resource sentre"
ahs_mhrh: "alberta health services - medicine hat regional hospital"
ahs_qeii: "alberta health services - queen elizabeth II hospital"
ahs_rah: "alberta health services - royal alexandra hospital"
ahs_reddr: "alberta health services - red deer regional hospital"
ahs_sturg: "alberta health services - sturgeoun-in transition-expect delays"
ahsglenrse: "alberta health services - glenrose rehabilitation hospital"
aitf_calg: "alberta innovates - technology futures - calgary"
aitf_c-fer: "alberta innovates - technology futures - c-fer technologies"
aitf_mw: "alberta innovates - technology futures - mill woods"
aitf_veg: "alberta innovates - technology futures - vegreville"
concordia: "concordia university college"
concordsem: "concordia lutheran seminary"
covenantgn: "covenant health - grey nuns community hospital"
covenantmh: "covenant health - misericordia community hospital"
cross: "alberta health services - cross cancer institute"
cuc: "canadian university college"
gprc_frvw: "grande prairie regional college - fairview"
gprc_gp: "grande prairie regional college - grande prairie"
gprc_int: "grande prairie regional college - internet"
gr_mac_acc: "macewan university - alberta college campus"
gr_mac_cac: "macewan university - centre for arts & communications"
gr_mac_int: "macewan university - internet"
gr_marc_soc: "macewan university south campus-on the move-expect delay"
gr_mac_tsv: "macewan university - technical services"
gr_macewan: "macewan university - city centre campus"
keyano: "keyano college"
kings: "king's university"
lakelnd_ll: "lakeland college lloydminster"
lakelnd_vr: "lakeland college vermilion"
neos_free: "neos free internet resources"
newman: "newman theological college"
norq_main: "norquest college - main building"
norq_west: "norquest college - westmount"
olds: "olds college"
red_deer_c: "red deer college"
taylor: "vanguard college - taylor"
uaarchives: "university of alberta archives"
uaaug: "university of alberta augustana"
uabard: "university of alberta book and record depository"
uabsj: "university of alberta bibliotheque saint-jean"
uabusiness: "university of alberta winspear business"
uaeduc: "university of alberta HT coutts education"
uahlthsc: "university of alberta JW scott health sciences"
uahss: "university of alberta rutherford - humanities & social science"
uainternet: "university of alberta internet"
ualaw: "university of alberta JA weir law"
uamath: "university of alberta cameron - mathematics"
uascitech: "university of alberta cameron - science & technology"
uasjc: "university of alberta st joseph's college"
iaspcoll: "university of alberta bruce peel special collections"
uatechserv: "university of alberta bibliographic services"
vanguard: "vanguard college"
