# Copied from the jupiter project
default: &default
  url: <%= Rails.application.config.solr %>
development:
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/development' %>
test:
  url: <%= ENV['SOLR_TEST_URL'] || 'http://localhost:8983/solr/test' %>
uat:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
